# ---
# - name: Deploy Docker App to Dev
#   hosts: dev
#   tasks:
#     - name: Ensure Docker container is running on Dev
#       docker_container:
#         name: my-web-app-dev
#         image: 9989228601/my-web-app:dev
#         state: started
#         recreate: yes
#         ports:  
#           - "80:80"
#       when: branch == 'dev'

# - name: Deploy Docker App to Prod
#   hosts: pro
#   tasks:
#     - name: Ensure Docker container is running on Prod
#       docker_container:
#         name: my-web-app-prod
#         image: 9989228601/my-web-app:prod
#         state: started
#         recreate: yes
#         ports:
#           - "80:80"
#       when: branch == 'prod'
---
- name: Deploy Docker App to Dev
  hosts: dev
  tasks:
    - name: Ensure the previous Docker container (dev) is removed
      docker_container:
        name: my-web-app-container-dev
        state: absent
      when: branch == 'dev'

    - name: Run new Docker container for dev
      docker_container:
        name: my-web-app-container-dev
        image: "9989228601/my-web-app:dev"
        state: started
        recreate: yes
        ports:
          - "80:80"
      when: branch == 'dev'

- name: Deploy Docker App to Prod
  hosts: pro
  tasks:
    - name: Ensure the previous Docker container (prod) is removed
      docker_container:
        name: my-web-app-container-prod
        state: absent
      when: branch == 'prod'

    - name: Run new Docker container for prod
      docker_container:
        name: my-web-app-container-prod
        image: "9989228601/my-web-app:prod"
        state: started
        recreate: yes
        ports:
          - "80:80"
      when: branch == 'prod'


