---
- name: Deploy Docker App to Prod
  hosts: pro  
  tasks:
    - name: Ensure the previous Docker container (prod) is removed
      docker_container:
        name: my-web-app-container-prod
        state: absent
      when: branch == 'prod'

    - name: Run new Docker container for prod
      docker_container:
        name: my-web-app-container-prod
        image: "9989228601/my-web-app:prod"
        state: started
        recreate: yes
        ports:
          - "80:80"
      when: branch == 'prod'
